var express = require('express')
var router = express.Router();
var path = require('path')
var register = require('./register/index')
var login = require('./login/index')
var search = require('./search/index')
var musiclist = require('./musiclist/index')
var record = require('./record/index')
var sheet = require('./sheet/index')
router.use('/login',login)
router.use('/register',register)
router.use('/search',search)
router.use('/musiclist',musiclist)
router.use('/record',record)
router.use('/sheet',sheet)
module.exports = router;
