git:
  depth: 500

notifications:
  email: false

sudo: false
language: python
cache: pip

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=mtgupf/essentia-builds:manylinux1_x86_64
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=mtgupf/essentia-builds:manylinux1_i686
           PRE_CMD=linux32

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build_wheels.sh
  - ls wheelhouse/

deploy:
  skip_cleanup: true
  provider: script
  script:
    python setup.py sdist;
    travis/deploy_transfer.sh
  on:
    branch: master
